#159250147 Export workouts
andela/wg-aces pull request #42
Opened 2018-08-29 13:45 UTC by archbishop12

#### What does this PR do?
The application should enable the user to export workouts.

#### Description of Task to be completed?
Exporting workouts as  a json file should be enabled.

#### Description of Task to be completed?
The user should be able to export 

#### How should this be manually tested?
After cloning this repository;
- login into the application
- Click workouts in the navigation bar and then workouts.
- Create a workout.
- After which create the click the options  and click `export as json`
- This download a son file.

#### What are the relevant pivotal tracker stories?
[#159250147](https://www.pivotaltracker.com/story/show/159250147)

#### Screenshots
<img width="1107" alt="screen shot 2018-08-29 at 16 43 30" src="https://user-images.githubusercontent.com/39958516/44791627-b7214100-abaa-11e8-808e-f38c8e9814ee.png">
<img width="704" alt="screen shot 2018-08-29 at 14 52 07" src="https://user-images.githubusercontent.com/39958516/44791645-c0aaa900-abaa-11e8-962c-878a8289614c.png">

2018-08-30 10:02 UTC, mutebironald approved these changes
I have pulled and tested it out.

2018-08-30 10:10 UTC, JaymesKat requested changes

2018-08-30 10:10 UTC, JaymesKat commented on wger/manager/views/workout.py
> +    list_object = []
This variable name is not very descriptive of the data we are expecting to export. Kindly rename it

2018-08-30 10:15 UTC, archbishop12 commented on wger/manager/views/workout.py
> +    list_object = []
Worked on it @Jpkat92

2018-08-30 11:16 UTC, JaymesKat approved these changes

2018-08-31 06:19 UTC, isheebo commented on wger/manager/models.py
> +    def get_json_representation(self):
nope, break this down my friend into smaller functions/methods. okay @archbishop12? 30 or less lines per function 😄

2018-08-31 06:19 UTC, isheebo commented on wger/manager/views/workout.py
> +import json
sort imports here

2018-08-31 08:05 UTC, archbishop12 commented on wger/manager/models.py
> +    def get_json_representation(self):
@isheebo I have broken down the function.

2018-08-31 08:06 UTC, archbishop12 commented on wger/manager/views/workout.py
> +import json
@isheebo I have worked on this

2018-08-31 12:01 UTC, merged