#159728074 Times entered should be standard
andela/wg-aces pull request #46
Opened 2018-08-30 07:31 UTC by Jpkat92

### What does this PR do?
Setups the application to use standard times

### Description of the task to be completed?
Adjust all points of the application where time is used to be standard.
Allow users to set their specific time zone under their profile settings

### How should this be manually tested?
- Clone the repository.
- Run migrations using the command `./manage.py migrate`
- Run the server `./manage.py runserver`
- Login and navigate to the top right  and select the `My preferences` option under the user profile section
- Click the option `Other settings` to reveal the field for setting the specific timezone
- Select your current time zone and click `Save`

### Any background context you want to provide?
Wger is used across the world and therefore all users should have the application's time setting conforming to their local time 

#### What are the relevant Pivotal tracker stories?
[#159728074](https://www.pivotaltracker.com/story/show/159728074)

#### Screenshots

Setting timezone on User Preferences page
<img width="1407" alt="screen shot 2018-08-29 at 19 40 59" src="https://user-images.githubusercontent.com/4680759/44802125-94e7ed00-abc3-11e8-861b-80cbbc50b940.png">

2018-08-30 09:04 UTC, matthewacha requested changes
You only set the time zone when a user changes their time zone preference `line 285 in wger/core/views/user.py`, which means whenever the session is reset the `TimezoneMiddleware` will deactivate timezone when a user next logins. I suggest you have `request.session['django_timezone']` set on login as well.

2018-08-30 12:17 UTC, Jpkat92 commented
@matthewacha Thank you for pointing that out, I added a login signal to set the user's preferred timezone.

2018-08-30 13:01 UTC, mutebironald approved these changes

2018-08-31 11:43 UTC, archbishop12 approved these changes
@Jpkat92 Good work here

2018-08-31 15:48 UTC, matthewacha approved these changes

2018-09-02 12:32 UTC, merged